version: '3.5'
services:
  jupyter-base:
    image: registry.gitlab.com/jafer1/learn-python
    container_name: learn-python
    environment:
      JUPYTER_TYPE: lab
      JUPYTER_BASE_URL: /jupyter
    ports:
      - "8888:8888"
